

public class ExceptionUser2 {
	public static void main(String[] args) throws Exception {
		ExceptionTest test = new ExceptionTest();
		test.call();
	}

}
